### ISSUE TITLE
packagist vendor group access

### ISSUE THREAD

**Issue by lachlan-00** [ampache/ampacheapi-php#4]
@Afterster are you able to update the packagist vendor group and add at least me to the profile?
![image](https://github.com/ampache/ampacheapi-php/assets/1305249/ff2482cb-5755-4df5-966d-66b318201f1a)

**Comment by Afterster** [comment]
Should be done now @lachlan-00. I wasn't even aware about having created such namespace :smiley:, I guess it is coming from an automatic migration by Composer. Let me know if it works.

**Comment by lachlan-00** [comment]
looks good, i can see it all now and the connections are updated.
![image](https://github.com/ampache/ampacheapi-php/assets/1305249/0c13de77-33ca-428a-af56-776ae2eeef7a)

After 6 i'm going to spend more time on updating this as it's been neglected by me for a long time
